#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_api_connexion:
  path: /api/connexion
  controller: App\Controller\ConnexionController::connexion

app_api_createuser:
  path: /api/CreateUser
  controller: App\Controller\ConnexionController::CreateUser
