#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_api_connexion:
  path: /api/connexion
  controller: App\Controller\ConnexionController::connexion

app_api_createuser:
  path: /api/CreateUser
  controller: App\Controller\ConnexionController::CreateUser

app_api_updatelibelleuserphoto:
  path: /api/updatelibelleuserphoto
  controller: App\Controller\ConnexionController::updatelibelleuserphoto

app_api_UpdateKeyPush:
  path: /api/UpdateKeyPush
  controller: App\Controller\ConnexionController::UpdateKeyPush

app_api_updatePhonenumber:
  path: /api/updatePhonenumber
  controller: App\Controller\ConnexionController::updatePhonenumber

app_api_searchtown:
  path: /api/SearchTown
  controller: App\Controller\HomeController::SearchTown

app_api_insertannonce:
  path: /api/InsertAnnonce
  controller: App\Controller\HomeController::InsertAnnonce

app_api_insertavis:
  path: /api/InsertAvis
  controller: App\Controller\HomeController::InsertAvis

app_api_Rechercher:
  path: /api/Rechercher
  controller: App\Controller\HomeController::Rechercher