#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_api_connexion:
  path: /api/connexion
  controller: App\Controller\ConnexionController::connexion

app_api_createuser:
  path: /api/CreateUser
  controller: App\Controller\ConnexionController::CreateUser

app_api_updatelibelleuserphoto:
  path: /api/updatelibelleuserphoto
  controller: App\Controller\ConnexionController::updatelibelleuserphoto

app_api_UpdateKeyPush:
  path: /api/UpdateKeyPush
  controller: App\Controller\ConnexionController::UpdateKeyPush

app_api_updatePhonenumber:
  path: /api/updatePhonenumber
  controller: App\Controller\ConnexionController::updatePhonenumber

app_api_searchtown:
  path: /api/SearchTown
  controller: App\Controller\HomeController::SearchTown

app_api_insertannonce:
  path: /api/InsertAnnonce
  controller: App\Controller\HomeController::InsertAnnonce

app_api_insertavis:
  path: /api/InsertAvis
  controller: App\Controller\HomeController::InsertAvis

app_api_Rechercher:
  path: /api/Rechercher
  controller: App\Controller\HomeController::Rechercher

app_api_ValidationAnnonce:
  path: /api/ValidationAnnonce
  controller: App\Controller\HomeController::ValidationAnnonce

app_api_InsertValidation:
  path: /api/InsertValidation
  controller: App\Controller\HomeController::InsertValidation

app_api_AfficherValidation:
  path: /api/AfficherValidation
  controller: App\Controller\HomeController::AfficherValidation

app_api_AfficherNotification:
  path: /api/AfficherNotification
  controller: App\Controller\HomeController::AfficherNotification

app_api_AfficherCountNotification:
  path: /api/AfficherCountNotification
  controller: App\Controller\HomeController::AfficherCountNotification

app_api_MarquerNotificationLu:
  path: /api/MarquerNotificationLu
  controller: App\Controller\HomeController::MarquerNotificationLu

app_api_ValidationAnnulationDemandeExpedition:
  path: /api/ValidationAnnulationDemandeExpedition
  controller: App\Controller\HomeController::ValidationAnnulationDemandeExpedition

app_api_AfficherAvis:
  path: /api/AfficherAvis
  controller: App\Controller\HomeController::AfficherAvis